### ISSUE TITLE
No Horizontal Scrollbars?

### ISSUE THREAD

**Issue by Venryx** [fuermosi777/react-free-scrollbar#1]
No horizontal scrollbars?

I'm assuming no, since I saw no references to scrollLeft in the source code. (whereas scrollUp is present)

Guess I'll work on this myself. (and not share it with anyone else : P -- not out of spite, haha, just cuz I'll probably be too lazy at first)

**Comment by Venryx** [comment]
Okay, here's my version with working vertical _and_ horizontal scrollbars: http://pastebin.com/zzkWgn7d

Plan to make a repo for it eventually, but for now just pastebin.

**Comment by fuermosi777** [comment]
Thanks. It now supports horizontal bar.
