### ISSUE TITLE
Missmatch version @0.3.1

### ISSUE THREAD

**Issue by bzemms** [fuermosi777/react-free-scrollbar#12]
Are you aware that in the latest [ `npm package` ](https://www.npmjs.com/package/react-free-scrollbar) -  the `dist/index.js` was't built with the latest `src/index.jsx` !!!!

**Comment by fuermosi777** [comment]
@bzemms sorry about that, fixed

**Comment by bzemms** [comment]
Thanks, when are you going to push it to `npm` ??
