### ISSUE TITLE
Not accounting for different scrollbar widths in different browsers

### ISSUE THREAD

**Issue by spoldman** [fuermosi777/react-free-scrollbar#6]
There is a strange line around when using this component as seen in the screenshot.

After some investigation I noticed that these are the original browser scrollbars, that led me to the hardcoded -15px adjustment to hide the scrollbars in the code. And as you can see here the width of scrollbars is different between operating system https://codepen.io/sambible/post/browser-scrollbar-widths. So this plugin is only working for me on a Mac.

![image](https://user-images.githubusercontent.com/10643226/29618112-8b24c7de-8806-11e7-8374-37c1ce523d67.png)

**Comment by fuermosi777** [comment]
Should be fixed now
